urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import TemplateView

from events.models import Calendar
from events.views.event_views import named_listing
from events.views.event_views import DayEventsListView
from events.views.event_views import HomeEventsListView
from events.views.event_views import MonthEventsListView
from events.views.event_views import WeekEventsListView
from events.views.event_views import YearEventsListView
from events.views.event_views import CalendarWidgetView

import django_saml2_auth

import core

from events.views.search import GlobalSearchView

admin.autodiscover()

ROBOTS_TEMPLATE = ''

if settings.DEV_MODE:
    ROBOTS_TEMPLATE = 'robots.dev.txt'
else:
    ROBOTS_TEMPLATE = 'robots.prod.txt'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^robots.txt', TemplateView.as_view(template_name=ROBOTS_TEMPLATE, content_type='text/plain')),
    url(r'^manager/', include('events.urls.manager')),
    url(r'^calendar/', include('events.urls.calendar')),
    url(r'^event/', include('events.urls.event_urls')),
    url(r'^category/', include('events.urls.category')),
    url(r'^tag/', include('events.urls.tag')),
    url(r'^help/$', TemplateView.as_view(template_name='events/static/help.html'), name='help'),
    url(r'^calendar-widget/(?P<view>[\w-]+)/(?P<size>[\w-]+)/(?P<year>[\d]+)/(?P<month>[\d]+)/$', CalendarWidgetView.as_view(), name='calendar-widget'),
    url(r'^calendar-widget/(?P<view>[\w-]+)/calendar/(?P<pk>\d+)/(?P<calendar_slug>[\w-]+)/(?P<size>[\w-]+)/(?P<year>[\d]+)/(?P<month>[\d]+)/$', CalendarWidgetView.as_view(), name='calendar-widget-by-calendar'),
    url(r'^esi/template/(?P<path>.*)', view=core.views.esi_template, name='esi-template'),
    url(r'^esi/(?P<model_name>[\w-]+)/(?P<object_id>[\d]+)/(calendar/(?P<calendar_id>[\d]+)/)?(?P<template_name>.*)', view=core.views.esi)
]

# Append search urls
urlpatterns += [
    url(r'^search/(?:feed\.(?P<format>[\w]+))?$', GlobalSearchView.as_view(), name='search_view'),
]


try:
    # Get Main Calendar so we have access to its slug:
    main_calendar = Calendar.objects.get(pk=settings.FRONT_PAGE_CALENDAR_PK)

    # Append Main Calendar url overrides
    urlpatterns += [
        url(r'^(feed\.(?P<format>[\w]+))?$',
            HomeEventsListView.as_view(),
            kwargs={'pk': settings.FRONT_PAGE_CALENDAR_PK, 'slug': main_calendar.slug},
            name='home'
        ),
        url(r'^(?P<year>[\d]+)/(?:feed\.(?P<format>[\w]+))?$',
            YearEventsListView.as_view(),
            kwargs={'pk': settings.FRONT_PAGE_CALENDAR_PK, 'slug': main_calendar.slug},
            name='main-calendar-year-listing'
        ),
        url(r'^(?P<year>[\d]+)/(?P<month>[\d]+)/(?:feed\.(?P<format>[\w]+))?$',
            MonthEventsListView.as_view(),
            kwargs={'pk': settings.FRONT_PAGE_CALENDAR_PK, 'slug': main_calendar.slug},
            name='main-calendar-month-listing'
        ),
        url(r'^(?P<year>[\d]+)/(?P<month>[\d]+)/(?P<day>[\d]+)/(?:feed\.(?P<format>[\w]+))?$',
            DayEventsListView.as_view(),
            kwargs={'pk': settings.FRONT_PAGE_CALENDAR_PK, 'slug': main_calendar.slug},
            name='main-calendar-day-listing'
        ),
        url(r'^week-of/(?P<year>[\d]+)/(?P<month>[\d]+)/(?P<day>[\d]+)/(?:feed\.(?P<format>[\w]+))?$',
            WeekEventsListView.as_view(),
            kwargs={'pk': settings.FRONT_PAGE_CALENDAR_PK, 'slug': main_calendar.slug},
            name='main-calendar-week-listing'
        ),
        url(r'^(?P<type>[\w-]+)/(?:feed\.(?P<format>[\w]+))?$',
            view=named_listing,
            kwargs={'pk': settings.FRONT_PAGE_CALENDAR_PK, 'slug': main_calendar.slug},
            name='main-calendar-named-listing'
        ),
    ]
except Exception:
    # An exception can occur here if the app db hasn't been set up yet.
    # Just skip registration of these URLs then
    pass

# Logins
if settings.USE_SAML:
    urlpatterns.insert(
        0,
        url(r'^sso/',
            include('django_saml2_auth.urls')
        )
    )
    urlpatterns.insert(
        1,
        url(r'^manager/login/$',
            django_saml2_auth.views.signin
        )
    )
    urlpatterns.insert(
        2,
        url(r'^admin/login/$',
            django_saml2_auth.views.signin
        )
    )


# Error handling
handler404 = 'core.views.handler404'
handler500 = 'core.views.handler500'

if settings.DEBUG:
    urlpatterns += [
        url(r'^debug/500-templ/$', TemplateView.as_view(template_name='500.html')),
        url(r'^debug/404-templ/$', TemplateView.as_view(template_name='404.html')),

    ]

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

events/models/promotion.py
from django.db import models

import random

class PromotionManager(models.Manager):
    def single_random(self):
        """
        Returns the first or a random promotion based on
        the kwargs passed into the function.
        """
        valid_count = self.filter(active=True).count()
        if valid_count == 0:
            return None
        idx = random.randrange(0, self.count())
        objects = self.get_queryset().filter(active=True)
        return objects[idx]


class Promotion(models.Model):
    title = models.CharField(max_length=255, null=False, blank=False)
    image = models.ImageField(null=False, blank=False)
    alt_text = models.CharField(max_length=500, null=False, blank=False)
    url = models.URLField(null=False, blank=False)
    active = models.BooleanField(null=False, blank=False, default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = PromotionManager()

    def __str__(self):
        return self.title

    def __unicode__(self):
        return self.title

events/forms/manager.py
from copy import deepcopy
import re

from django import forms
from django.contrib.auth.models import User
from django.forms.models import inlineformset_factory
from django.core.exceptions import ValidationError
from taggit.models import Tag


from core.forms import RequiredModelFormSet
from core.utils import generate_unique_slug
from events.forms.fields import InlineLDAPSearchField
from events.forms.fields import CustomImageWidget
from events.forms.widgets import BootstrapSplitDateTimeWidget
from events.forms.widgets import TaggitField
from events.forms.widgets import Wysiwyg
from events.forms.fields import CalendarChoiceField
from events.functions import is_date_in_valid_range
from events.functions import get_earliest_valid_date
from events.functions import get_latest_valid_date
from events.models import Calendar
from events.models import Event
from events.models import EventInstance
from events.models import Location
from events.models import Category
from events.models import Promotion
from events.models import FeaturedEvent
from events.models import get_main_calendar

import settings


class ModelFormStringValidationMixin(forms.ModelForm):
    """
    Mixin that trims any string values passed through
    the given form's fields.
    """
    def clean(self):
        cleaned_data = super(ModelFormStringValidationMixin, self).clean()

        for field in cleaned_data:
            val = cleaned_data.get(field)
            if isinstance(val, str):
                val = val.strip()
                cleaned_data[field] = val

        return cleaned_data


class ModelFormUtf8BmpValidationMixin(forms.ModelForm):
    """
    Mixin that strips characters outside of the Basic Multilingual Plane
    out of string values.
    """
    def clean(self):
        cleaned_data = super(ModelFormUtf8BmpValidationMixin, self).clean()
        cleaned_data_copy = deepcopy(cleaned_data)  # Make a copy because python won't let you modify a dict while it's being iterated

        form_fields = self.fields

        for field, val in cleaned_data.items():
            required = form_fields[field].required

            if isinstance(val, str):
                cleaned_data_copy[field] = re.sub(r'[^\u0000-\uD7FF\uE000-\uFFFF]', '', cleaned_data_copy[field])

                # Delete any cleaned data that are now empty and let the user know
                if not cleaned_data_copy[field]:
                    if required:
                        self._errors[field] = self.error_class(['Sorry, special characters are not permitted here. Please enter a different value.'])
                    del cleaned_data_copy[field]

        return cleaned_data_copy


class CalendarForm(ModelFormStringValidationMixin, forms.ModelForm):
    """
    Form for the Calendar
    """
    def __init__(self, *args, **kwargs):
        super(CalendarForm, self).__init__(*args, **kwargs)
        calendar = kwargs['instance']
        # Disable the title field for the main calendar
        if calendar and calendar.is_main_calendar:
            self.fields['title'].widget.attrs['readonly'] = True

    def clean_title(self):
        # Prevent main calendar title from being modified
        calendar = self.instance
        title = self.cleaned_data['title']

        if not calendar.is_main_calendar and title.lower() in settings.DISALLOWED_CALENDAR_TITLES:
            #TODO Make a help section explaining which titles are not allowed and link to it.
            raise ValidationError(f"The calendar title you entered is not allowed.")

        if calendar and calendar.is_main_calendar:
            return calendar.title
        else:
            return self.cleaned_data['title']

    class Meta:
        model = Calendar
        fields = (
            'title',
            'description',
            'active',
            'trusted',
            'desktop_header_image',
            'mobile_header_image',
        )
        widgets = {
            'desktop_header_image': CustomImageWidget,
            'mobile_header_image': CustomImageWidget
        }


class CalendarSubscribeForm(forms.ModelForm):
    """
    Subscribe one or more calendars to another calendar
    """
    calendars = forms.ModelMultipleChoiceField(queryset=Calendar.objects.none(), label='Calendars to subscribe:')

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super(CalendarSubscribeForm, self).__init__(*args, **kwargs)
        self.fields['calendars'].queryset = user.editable_calendars.all()

    class Meta(CalendarForm.Meta):
        model = Calendar
        fields = ('calendars',)


class EventForm(ModelFormStringValidationMixin, ModelFormUtf8BmpValidationMixin, forms.ModelForm):
    """
    Form for an Event
    """
    def __init__(self, *args, **kwargs):
        initial = kwargs.pop('initial')
        user_calendars = initial.pop('user_calendars')
        super(EventForm, self).__init__(*args, **kwargs)
        self.fields['calendar'].queryset = user_calendars


        self.fields['title'].widget = forms.TextInput(attrs={"spellcheck": "true"})
        self.fields['description'].widget = Wysiwyg()
        self.fields['tags'].widget = TaggitField()

        instance = kwargs['instance']
        if instance and instance.created_from:
            if instance.created_from.title is instance.title:
                self.fields['new_title'] = forms.CharField(required=False, initial=instance.title)
                self.fields['new_title'].widget.attrs['disabled'] = 'disabled'

            if instance.created_from.description is instance.description:
                self.fields['new_description'] = forms.CharField(required=False,
                                                                 initial=instance.description,
                                                                 widget=forms.Textarea(attrs={'disabled': 'disabled', 'class': 'wysiwyg'}))

        self.fields['submit_to_calendar'] = CalendarChoiceField(queryset=Calendar.objects.all(), required=False)
        obj = self.instance
        copied_event = obj.get_copied_event()
        if copied_event is not None:
            self.fields['submit_to_calendar'].initial = copied_event.calendar


    title = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Event Title'}))
    calendar = forms.ModelChoiceField(queryset=Calendar.objects.none(), empty_label=None)
    registration_checkbox = forms.BooleanField(required=False)

    def clean(self):
        self._validate_unique = True
        cleaned_data = super(EventForm, self).clean()

        registration_checkbox = cleaned_data.get('registration_checkbox')
        registration_link = cleaned_data.get('registration_link')
        registration_info = cleaned_data.get('registration_info')

        if not registration_checkbox:
            cleaned_data['registration_link'] = None
            cleaned_data['registration_info'] = None

        if registration_checkbox and registration_info == None:
            cleaned_data['registration_info'] = None

        # Remove '&quot;' and '"' characters from tag phrases, and strip
        # characters that don't match our whitelist.
        tags = cleaned_data.get('tags', [])

        if len(tags) > 5:
            self.errors['tags'] = self.error_class(['Please provide no more than 5 tags that best describe your event.'])

        for key, tag in enumerate(tags):
            tags[key] = re.sub(r'([^a-zA-Z0-9 -!$#%&+|:?\'])|(&quot;?)', '', tag)

        if registration_checkbox and not registration_link:
            self._errors['registration_link'] = self.error_class(['A registration link is required if the registration checkbox is checked.'])

        return cleaned_data

    class Meta:
        model = Event
        fields = ('calendar', 'title', 'state', 'description', 'contact_name', 'contact_email', 'contact_phone', 'category', 'tags', 'registration_link', 'registration_info')


class EventInstanceForm(ModelFormStringValidationMixin, ModelFormUtf8BmpValidationMixin, forms.ModelForm):
    """
    Form for the EventInstance
    """
    start = forms.DateTimeField(
        widget=BootstrapSplitDateTimeWidget(
            attrs={
                'date_class': 'form-control field-date',
                'time_class': 'form-control field-time',
                'date_placeholder': 'mm/dd/yyyy',
                'time_placeholder': '12:00 AM',
                'autocomplete': 'off'
            }
        ),
        input_formats=[
            '%m/%d/%Y %I:%M %p', # '10/25/2006 2:30 PM'
            '%m/%d/%Y %I:%M',    # '10/25/2006 14:30'
        ],
    )
    end = forms.DateTimeField(
        widget=BootstrapSplitDateTimeWidget(
            attrs={
                'date_class': 'form-control field-date',
                'time_class': 'form-control field-time',
                'date_placeholder': 'mm/dd/yyyy',
                'time_placeholder': '12:00 AM',
                'autocomplete': 'off'
            }
        ),
        input_formats=[
            '%m/%d/%Y %I:%M %p', # '10/25/2006 2:30 PM'
            '%m/%d/%Y %I:%M',    # '10/25/2006 14:30'
        ],
    )

    until = forms.DateField(required=False)
    new_location_title = forms.CharField(required=False)
    new_location_room = forms.CharField(required=False)
    new_location_url = forms.URLField(required=False)
    physical_checkbox = forms.BooleanField(required=False)
    virtual_checkbox = forms.BooleanField(required=False)

    def clean(self):
        cleaned_data = super(EventInstanceForm, self).clean()

        start = cleaned_data.get('start')
        end = cleaned_data.get('end')
        until = cleaned_data.get('until')
        location = cleaned_data.get('location')
        virtual_url = cleaned_data.get('virtual_url')
        new_location_title = cleaned_data.get('new_location_title')
        new_location_url = cleaned_data.get('new_location_url')
        physical_checkbox = cleaned_data.get('physical_checkbox')

templates/events/manager/featured_event/create.html
{% extends 'events/manager/base.html' %}
{% load widget_tweaks %}

{% block alerts %}
  {{ block.super }}
  {% if form.non_field_errors %}
    <div class="alert alert-danger">
      <strong>Error: </strong>
      {{ form.non_field_errors }}
    </div>
  {% endif %}
{% endblock %}

{% block title %}Create a Featured Event | {{ block.super }}{% endblock %}

{% block content_title %}
  <div class="col-12">
    <h1 class="h2 mb-2">Create a Featured Event</h1>
  </div>
{% endblock %}

{% block content_subheader %}
  <div class="row">
    <div class="col-md-12">
      <p class="lead mb-4">
        Use the form below to select a featured event.
      </p>
    </div>
  </div>
{% endblock %}

{% block content_body %}
<div class="row">
  <div class="col-xl-10 offset-xl-1">
    <form action="{% url 'events.views.manager.featured_event.create' %}" method="post" id="featured-event-create" enctype="multipart/form-data">
      {% csrf_token %}
      <!-- Event Field -->
      <div class="form-group row{% if form.event.errors %} has-danger{% endif %}">
        <div class="col-md-3 col-xl-4 text-md-right mb-2">
          <label class="font-weight-bold col-form-label" for="id_title">Event to Feature</label>
        </div>
        <div class="col-md-6 col-xl-8">
          {{ form.event|add_class:"form-control"|add_error_class:"form-control-danger"}}
          {% if form.event.errors %}
            {% for error in form.title.errors %}
              <div class="form-control-feedback">{{ error }}</div>
            {% endfor %}
          {% endif %}
        </div>
      </div>
      <!-- End event field -->
      <!-- Desktop image field -->
      <div class="form-group row{% if form.desktop_feature_image.errors %} has-danger{% endif %}">
        <div class="col-md-3 col-xl-4 text-md-right mb-2">
          <label class="font-weight-bold col-form-label" for="id_image">Desktop Image</label>
        </div>
        <div class="col-md-6 col-xl-8">
          {{ form.desktop_feature_image|add_class:"form-control"|add_error_class:"form-control-danger" }}
          {% if form.desktop_feature_image.errors %}
            {% for error in form.desktop_feature_image.errors %}
              <div class="form-control-feedback">{{ error }}</div>
            {% endfor %}
          {% endif %}
        </div>
      </div>
      <!-- End desktop image field -->
      <!-- Mobile image field -->
      <div class="form-group row{% if form.desktop_feature_image.errors %} has-danger{% endif %}">
        <div class="col-md-3 col-xl-4 text-md-right mb-2">
          <label class="font-weight-bold col-form-label" for="id_image">Mobile Image</label>
        </div>
        <div class="col-md-6 col-xl-8">
          {{ form.mobile_feature_image|add_class:"form-control"|add_error_class:"form-control-danger" }}
          {% if form.mobile_feature_image.errors %}
            {% for error in form.mobile_feature_image.errors %}
              <div class="form-control-feedback">{{ error }}</div>
            {% endfor %}
          {% endif %}
        </div>
      </div>
      <!-- End mobile image field -->
      <!-- Start date field -->
      <div class="form-group row{% if form.desktop_feature_image.errors %} has-danger{% endif %}">
        <div class="col-md-3 col-xl-4 text-md-right mb-2">
          <label class="font-weight-bold col-form-label" for="id_image">Start Date</label>
        </div>
        <div class="col-md-6 col-xl-8">
          {{ form.start_date|add_class:"form-control"|add_error_class:"form-control-danger"|attr:"type:date"}}
          {% if form.start_date.errors %}
            {% for error in form.start_date.errors %}
              <div class="form-control-feedback">{{ error }}</div>
            {% endfor %}
          {% endif %}
        </div>
      </div>
      <!-- End start date field -->

      <!-- End active field -->
      <div class="form-group row">
        <div class="col-md-9 offset-md-3 col-xl-8 offset-xl-4">
          <button type="submit" class="btn btn-primary btn-block-xs">Create Featured Event</button>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock %}

{% block footer_scripts %}
  {{ block.super }}
{% endblock %}

templates/events/manager/featured_event/delete.html
{% extends 'events/manager/modify-object.html' %}
{% load widget_tweaks %}

{% block title %}Delete Featured Event: {{ featured_event.event.title }} | {{ block.super }}{% endblock %}

{% block content_title %}
  <div class="col-12">
    <h1 class="h2 mb-4">Delete Featured Event: <span class="font-weight-normal">{{ featured_event.event.title }}</span></h1>
  </div>
{% endblock %}

{% block content_form_id %}events.views.manager.featured_event.delete{% endblock %}

{% block content_form_body %}
  {% csrf_token %}
  <p>
    Are you sure you want to delete this featured event? There is no undo!
  </p>
{% endblock %}

{% block content_form_footer %}
  <button type="submit" class="btn btn-danger btn-sm">Delete Featured Event</button>
  <a href="{% url 'events.views.manager.featured_event.list' %}" class="btn btn-default btn-sm" data-dismiss="modal">Cancel</a>
{% endblock %}

{% block footer_scripts %}
  {{ block.super }}
{% endblock %}

templates/events/manager/featured_event/list.html
{% extends 'events/manager/base.html' %}
{% load widgets %}

{% block title %}All Featured Events | {{ block.super }}{% endblock %}

{% block content_title %}
  <div class="col-12">
    <h1 class="h2">All Featured Events</h1>
  </div>
{% endblock %}

{% block content_subheader %}
  {% block content_subheader_text %}
    <div class="alert alert-info">
      <p class="mb-0"><span class="fas fa-info-circle"></span> The active featured event will be display on the home page until the next featured event (based on the "start" field) becomes active, or all instances of the featured event has past. </p>
    </div>
  {% endblock %}
{% endblock %}

{% block content_body %}
  <div class="row justify-content-between">
    <div class="col-12 col-md-auto">
      <a class="btn btn-primary mb-3" href="{% url 'events.views.manager.featured_event.create' %}">
        <span class="fa fa-plus mr-1" aria-hidden="true"></span>Create New Featured Event
      </a>
    </div>
  </div>
  {% if featured_events.count > 0 %}
  <div class="card my-4">
    <table class="list-manager-table table">
      <thead>
        <tr>
          <th class="title">Featured Event</th>
          <th>Active</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
      {% for featured_event in featured_events %}
        <tr>
          <td class="title">
            <a href="{% url 'events.views.manager.featured_event.update' featured_event.pk %}">{{ featured_event.event.title }} ({{featured_event.start_date}})</a>
          </td>
          <td>
            {% if promotion.active %}
              <span class="fas fa-check-circle text-success"></span>
            {% else %}
              <span class="fas fa-times-circle text-danger"></span>
            {% endif %}
          </td>
          <td>
            <div class="dropdown">
              <a class="btn btn-default btn-sm dropdown-toggle" href="#" role="button" id="promotionSelectDropdownMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Select
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="featured_eventSelectDropdownMenu">
                <a class="dropdown-item" href="{% url 'events.views.manager.featured_event.update' featured_event.pk %}">
                  <span class="fa fa-pencil-alt fa-fw mr-1" aria-hidden="true"></span>Edit Featured Event
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'events.views.manager.featured_event.delete' featured_event.pk %}">
                  <span class="fas fa-trash fa-fw mr-1" aria-hidden="true"></span>Delete Featured Event
                </a>
              </div>
            </div>
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>

  {% pager paginator=paginator current_page=request.GET.page url=request.build_absolute_uri %}

  {% else %}
  <div class="alert alert-info">
    No featured events found. Want to <a class="alert-link" href="{% url 'events.views.manager.featured_event.create' %}">create one?</a>
  </div>
  {% endif %}
{% endblock %}

templates/events/manager/featured_event/update.html
{% extends 'events/manager/base.html' %}
{% load widget_tweaks %}

{% block alerts %}
  {{ block.super }}
  {% if form.non_field_errors %}
    <div class="alert alert-danger">
      <strong>Error: </strong>
      {{ form.non_field_errors }}
    </div>
  {% endif %}
{% endblock %}

{% block title %}{% block edit_title %}Edit Featured Event{% endblock %}: {{ promotion.title }} | {{ block.super }}{% endblock %}

{% block content_title %}
  <div class="col-lg-8">
    <h1 class="h2 mb-4">Edit featured event: <span class="font-weight-normal">{{ featured_event.event.title }}</span></h1>
  </div>
{% endblock %}

{% block content_subheader %}{% endblock %}

{% block content_body %}
<div class="row">
  <div class="col-xl-10 offset-xl-1">
    <form action="{% url 'events.views.manager.featured_event.update' object.pk %}" method="post" id="featured-event-create" enctype="multipart/form-data">
      {% csrf_token %}
      <!-- Event Field -->
      <div class="form-group row{% if form.event.errors %} has-danger{% endif %}">
        <div class="col-md-3 col-xl-4 text-md-right mb-2">
          <label class="font-weight-bold col-form-label" for="id_title">Event to Feature</label>
        </div>
        <div class="col-md-6 col-xl-8">
          {{ form.event|add_class:"form-control"|add_error_class:"form-control-danger"}}
          {% if form.event.errors %}
            {% for error in form.title.errors %}
              <div class="form-control-feedback">{{ error }}</div>
            {% endfor %}
          {% endif %}
        </div>
      </div>
      <!-- End event field -->
      <!-- Desktop image field -->
      <div class="form-group row{% if form.desktop_feature_image.errors %} has-danger{% endif %}">
        <div class="col-md-3 col-xl-4 text-md-right mb-2">
          <label class="font-weight-bold col-form-label" for="id_desktop_featured_image">Desktop Image</label>
        </div>
        <div class="col-md-6 col-xl-8">
          {{ form.desktop_feature_image|add_class:"form-control"|add_error_class:"form-control-danger" }}
          {% if form.desktop_feature_image.errors %}
            {% for error in form.desktop_feature_image.errors %}
              <div class="form-control-feedback">{{ error }}</div>
            {% endfor %}
          {% endif %}
        </div>
      </div>
      <!-- End desktop image field -->
      <!-- Mobile image field -->
      <div class="form-group row{% if form.mobile_feature_image.errors %} has-danger{% endif %}">
        <div class="col-md-3 col-xl-4 text-md-right mb-2">
          <label class="font-weight-bold col-form-label" for="id_mobile_featured_image">Mobile Image</label>
        </div>
        <div class="col-md-6 col-xl-8">
          {{ form.mobile_feature_image|add_class:"form-control"|add_error_class:"form-control-danger" }}
          {% if form.mobile_feature_image.errors %}
            {% for error in form.mobile_feature_image.errors %}
              <div class="form-control-feedback">{{ error }}</div>
            {% endfor %}
          {% endif %}
        </div>
      </div>
      <!-- End mobile image field -->
      <!-- Start date field -->
      <div class="form-group row{% if form.start_date.errors %} has-danger{% endif %}">
        <div class="col-md-3 col-xl-4 text-md-right mb-2">
          <label class="font-weight-bold col-form-label" for="id_start_date">Start Date</label>
        </div>
        <div class="col-md-6 col-xl-8">
          {{ form.start_date|add_class:"form-control"|add_error_class:"form-control-danger"}}
          {% if form.start_date.errors %}
            {% for error in form.start_date.errors %}
              <div class="form-control-feedback">{{ error }}</div>
            {% endfor %}
          {% endif %}
        </div>
      </div>
      <!-- End start date field -->

      <!-- End active field -->
      <div class="form-group row">
        <div class="col-md-9 offset-md-3 col-xl-8 offset-xl-4">
          <button type="submit" class="btn btn-primary btn-block-xs">Update Featured Event</button>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock %}

{% block footer_scripts %}
  {{ block.super }}
{% endblock %}